export const FETCH_YOUTUBEAPI_STARTED = 'FETCH_YOUTUBEAPI_STARTED';
export const FETCH_YOUTUBEAPI_FINISHED = 'FETCH_YOUTUBEAPI_FINISHED';
export const FETCH_YOUTUBEAPI_FAILED = 'FETCH_YOUTUBEAPI_FAILED';